[features]
seeds = false
skip-lint = false
[programs.localnet]
waffle_maker = "5qFnsyF5zo6NsoGCfj2HndizxFBAXwe3YbfzppfhTNz3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/eemcs/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
